### ISSUE TITLE
s/view/show/ in Mouse.position example of Elm Signals post

### ISSUE THREAD

**Issue by walkermatt** [yang-wei/yang-wei.github.io#1]
Hi,

I've working through your Elm Signals post and noticed that the Mouse.position example uses `view` when it should be `show`:

```
import Mouse

main : Signal Element
main =
    Signal.map view Mouse.position
```

Should be:

```
import Mouse

main : Signal Element
main =
    Signal.map show Mouse.position
```

Thanks for the post, I'm finding it a great introduction as the examples are so concise :+1:

**Comment by yang-wei** [comment]
@walkermatt Thanks =) Fixed. Glad you enjoyed that
